### ISSUE TITLE
message d'erreur au lancement

### ISSUE THREAD

**Issue by eric1959** [seventh/FlammeRouge#11]
Eric    Warolus
7540 Rumillies
     Belgique

warolus@belgacom.net

Bonjour, 

j'ai lancé le jeu Flamme rouge sous python 3.8.1 mais j'obtiens ce message d'erreur : 

Traceback (most recent call last):
   File "Desktop\flamme\flamme_rouge.py", line 1186, in (module)
      principal(nb_humains)
   File "Desktop\flamme\flamme_rouge.py", line 1073, in principal
      tracé, nb_tours = choisir_course("courses.json")
   File "Desktop\flamme\flamme_rouge.py", line 55, in choisir_course 
      with open(chemin, "rt") as entrée:
FileNotFoundError: [Errno 2] No such file or directory: 'courses.json'

Salutations

**Comment by seventh** [comment]
Bonjour, cela devrait être désormais corrigé.

Merci de votre intérêt pour cette modeste simulation.

Guillaume

**Comment by eric1959** [comment]
Bonjour , merci pour votre réactivité. Mais je reçois un autre message d'erreur au lancement : 
Traceback (most recent call last):
File "Desktop\flamme\flamme_rouge.py", line 1159, in (module)
principal(nb_humains)
File "Desktop\flamme\flamme_rouge.py", line 1045, in principal
tracé, nb_tours = choisir_course(
File "Desktop\flamme\flamme_rouge.py", line 63, in choisir_course
for nom_tronçon, tronçon in parcours ["tronçons"].items() : 
KeyError: 'tronçons'

Salutations

P/S comment se fait-il que d'autres personnes ont réussi a faire fonctionner votre programme ? est-ce dû à la version de Python que j'emploie ?
